import { Router } from "express";
import { authenticate } from "../middleware/auth.middleware.js";
import { allowRoles } from "../middleware/roles.js";
import { adminDashboard } from "../controllers/dashboard.controller.js";
import { users, createUser, restaurants, orders, approveRestaurant, createRestaurant, assignDelivery, menu } from "../controllers/admin.controller.js";
import { createMenuItem, updateMenuItem, deleteMenuItem } from "../controllers/restaurant.controller.js";
import { listNotifications, markRead } from "../controllers/notification.controller.js";
import { adminAnalytics, adminSettings, updateAdminSettings } from "../controllers/analytics.controller.js";
const router = Router();
router.use(authenticate, allowRoles("admin"));
router.get("/dashboard", adminDashboard);
router.get("/analytics", adminAnalytics);
router.get("/settings", adminSettings);
router.patch("/settings", updateAdminSettings);
router.get("/notifications", listNotifications);
router.patch("/notifications/:id/read", markRead);
router.get("/users", users);
router.post("/users", createUser);
router.get("/restaurants", restaurants);
router.post("/restaurants", createRestaurant);
router.get("/restaurants/:restaurantId/menu", menu);
router.post("/restaurants/:restaurantId/menu", createMenuItem);
router.patch("/menu/:id", updateMenuItem);
router.delete("/menu/:id", deleteMenuItem);
router.get("/orders", orders);
router.patch("/restaurants/:id/approve", approveRestaurant);
router.patch("/orders/:orderId/assign-delivery", assignDelivery);
export default router;
