import { Router } from "express";
import { authenticate } from "../middleware/auth.js";
import { allowRoles } from "../middleware/roles.js";
import { customerDashboard } from "../controllers/dashboard.controller.js";
import { createOrder, customerOrders, getOrder } from "../controllers/order.controller.js";
import { listNotifications, markRead } from "../controllers/notification.controller.js";
import { favourites, addFavourite, removeFavourite, wallet, topUpWallet, offers, validateOffer, updateProfile, customerWalletOrderSync } from "../controllers/customer.controller.js";
const router = Router();
router.use(authenticate, allowRoles("customer"));
router.get("/dashboard", customerDashboard);
router.post("/orders", createOrder);
router.get("/orders", customerOrders);
router.get("/orders/:id", getOrder);
router.get("/notifications", listNotifications);
router.patch("/notifications/:id/read", markRead);
router.get("/favourites", favourites);
router.post("/favourites", addFavourite);
router.delete("/favourites/:id", removeFavourite);
router.get("/wallet", wallet);
router.post("/wallet/top-up", topUpWallet);
router.post("/wallet/sync-orders", customerWalletOrderSync);
router.get("/offers", offers);
router.post("/offers/validate", validateOffer);
router.patch("/profile", updateProfile);
export default router;
