export const categories = [
  {
    id: 1,
    name: "Biryani",
    emoji: "🍛",
    color: "#fff0e8",
    description: "Aromatic & spicy",
  },
  {
    id: 2,
    name: "Pizza",
    emoji: "🍕",
    color: "#fff5d8",
    description: "Cheesy goodness",
  },
  {
    id: 3,
    name: "Burger",
    emoji: "🍔",
    color: "#ffe9d7",
    description: "Juicy & loaded",
  },
  {
    id: 4,
    name: "South Indian",
    emoji: "🥞",
    color: "#eaf8ed",
    description: "Fresh & traditional",
  },
  {
    id: 5,
    name: "Chinese",
    emoji: "🥡",
    color: "#ffe8e8",
    description: "Wok favourites",
  },
  {
    id: 6,
    name: "North Indian",
    emoji: "🫓",
    color: "#fff0df",
    description: "Rich & flavorful",
  },
  {
    id: 7,
    name: "Desserts",
    emoji: "🍰",
    color: "#f9eaff",
    description: "Sweet cravings",
  },
  {
    id: 8,
    name: "Healthy",
    emoji: "🥗",
    color: "#e8f8ef",
    description: "Fresh & healthy",
  },
  {
    id: 9,
    name: "Chicken",
    emoji: "🍗",
    color: "#ffe9e0",
    description: "Protein packed",
  },
  {
    id: 10,
    name: "Drinks",
    emoji: "🥤",
    color: "#e8f3ff",
    description: "Cool & refreshing",
  },
  {
    id: 11,
    name: "Shawarma",
    emoji: "🌯",
    color: "#fff1e6",
    description: "Smoky & loaded",
  },
  {
    id: 12,
    name: "Momos",
    emoji: "🥟",
    color: "#eef7ff",
    description: "Steamed & spicy",
  },
  {
    id: 13,
    name: "Street Food",
    emoji: "🌮",
    color: "#fff6d9",
    description: "Desi favourites",
  },
  {
    id: 14,
    name: "Cakes",
    emoji: "🎂",
    color: "#f9edff",
    description: "Freshly baked",
  },
];
const baseRestaurants = [
  {
    id: 1,
    name: "SS Hyderabad Biryani",
    cuisine: "Biryani • North Indian • Chinese",
    tags: ["Biryani", "Chicken", "North Indian"],
    location: "Anna Nagar, Chennai",
    rating: 4.8,
    ratingCount: "8.4K+",
    deliveryTime: "25-30 mins",
    deliveryMinutes: 28,
    priceForTwo: "₹400 for two",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjmm3PWk-6eCVmf3HkORmbuE-77ByNC2746mHTlycgYQ&s=10",
    offer: "50% OFF up to ₹100",
    promoted: true,
    veg: false,
    distance: "2.1 km",
    distanceValue: 2.1,
    isOpen: true,
    freeDelivery: true,
    deliveryFee: 0,
    popular: true,
  },
  {
    id: 2,
    name: "The Pizza Factory",
    cuisine: "Pizza • Italian • Fast Food",
    tags: ["Pizza", "Fast Food"],
    location: "T Nagar, Chennai",
    rating: 4.6,
    ratingCount: "5.2K+",
    deliveryTime: "20-25 mins",
    deliveryMinutes: 23,
    priceForTwo: "₹500 for two",
    image:
      "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1000&q=85",
    offer: "₹125 OFF",
    promoted: true,
    veg: true,
    distance: "1.8 km",
    distanceValue: 1.8,
    isOpen: true,
    freeDelivery: true,
    deliveryFee: 0,
    popular: true,
  },
  {
    id: 3,
    name: "Burger Singh",
    cuisine: "Burgers • American • Fast Food",
    tags: ["Burger", "Fast Food", "Chicken"],
    location: "Velachery, Chennai",
    rating: 4.5,
    ratingCount: "4.1K+",
    deliveryTime: "25-30 mins",
    deliveryMinutes: 29,
    priceForTwo: "₹350 for two",
    image:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1000&q=85",
    offer: "20% OFF",
    promoted: false,
    veg: false,
    distance: "3.2 km",
    distanceValue: 3.2,
    isOpen: true,
    freeDelivery: false,
    deliveryFee: 39,
    popular: true,
  },
  {
    id: 4,
    name: "Saravana Bhavan",
    cuisine: "South Indian • Breakfast • Pure Veg",
    tags: ["South Indian", "Healthy"],
    location: "Adyar, Chennai",
    rating: 4.7,
    ratingCount: "9.8K+",
    deliveryTime: "20-25 mins",
    deliveryMinutes: 22,
    priceForTwo: "₹300 for two",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4YwMQYby4-XcLfsz_5jFwwM-nY8lzc29W5EfkV0lbCQ&s=10",
    offer: "20% OFF up to ₹75",
    promoted: true,
    veg: true,
    distance: "2.5 km",
    distanceValue: 2.5,
    isOpen: true,
    freeDelivery: true,
    deliveryFee: 0,
    popular: true,
  },
  {
    id: 5,
    name: "Wok This Way",
    cuisine: "Chinese • Asian • Thai",
    tags: ["Chinese"],
    location: "Nungambakkam, Chennai",
    rating: 4.4,
    ratingCount: "3.7K+",
    deliveryTime: "30-35 mins",
    deliveryMinutes: 34,
    priceForTwo: "₹550 for two",
    image:
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1000&q=85",
    offer: "Flat ₹100 OFF",
    promoted: false,
    veg: false,
    distance: "4.2 km",
    distanceValue: 4.2,
    isOpen: true,
    freeDelivery: true,
    deliveryFee: 0,
    popular: false,
  },
  {
    id: 6,
    name: "Punjabi Rasoi",
    cuisine: "North Indian • Mughlai • Punjabi",
    tags: ["North Indian", "Chicken"],
    location: "Guindy, Chennai",
    rating: 4.6,
    ratingCount: "6.3K+",
    deliveryTime: "25-30 mins",
    deliveryMinutes: 27,
    priceForTwo: "₹450 for two",
    image:
      "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=1000&q=85",
    offer: "30% OFF",
    promoted: false,
    veg: true,
    distance: "3.5 km",
    distanceValue: 3.5,
    isOpen: true,
    freeDelivery: false,
    deliveryFee: 29,
    popular: true,
  },
  {
    id: 7,
    name: "Cream Stone",
    cuisine: "Desserts • Ice Cream • Beverages",
    tags: ["Desserts", "Drinks"],
    location: "Besant Nagar, Chennai",
    rating: 4.8,
    ratingCount: "7.1K+",
    deliveryTime: "15-20 mins",
    deliveryMinutes: 18,
    priceForTwo: "₹300 for two",
    image:
      "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1000&q=85",
    offer: "Buy 1 Get 1",
    promoted: true,
    veg: true,
    distance: "1.2 km",
    distanceValue: 1.2,
    isOpen: true,
    freeDelivery: true,
    deliveryFee: 0,
    popular: true,
  },
  {
    id: 8,
    name: "Green Bowl",
    cuisine: "Healthy • Salads • Continental",
    tags: ["Healthy"],
    location: "OMR, Chennai",
    rating: 4.5,
    ratingCount: "2.8K+",
    deliveryTime: "20-25 mins",
    deliveryMinutes: 24,
    priceForTwo: "₹450 for two",
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1000&q=85",
    offer: "25% OFF",
    promoted: false,
    veg: true,
    distance: "3.8 km",
    distanceValue: 3.8,
    isOpen: true,
    freeDelivery: true,
    deliveryFee: 0,
    popular: false,
  },
];
const baseMenuItems = [
  {
    id: 101,
    restaurantId: 1,
    name: "Chicken Biryani",
    category: "Biryani",
    description:
      "Aromatic basmati rice with tender chicken and rich spices.",
    price: 249,
    originalPrice: 299,
    rating: 4.8,
    ratingCount: "2.4K+",
    bestseller: true,
    veg: false,
    spicy: true,
    calories: 520,
    image:
      "https://images.unsplash.com/photo-1563379091339-03246963d96c?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: 102,
    restaurantId: 1,
    name: "Mutton Biryani",
    category: "Biryani",
    description:
      "Slow cooked mutton layered with fragrant basmati rice.",
    price: 329,
    originalPrice: 379,
    rating: 4.7,
    ratingCount: "1.8K+",
    bestseller: true,
    veg: false,
    spicy: true,
    calories: 610,
    image:
      "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: 103,
    restaurantId: 2,
    name: "Farmhouse Pizza",
    category: "Pizza",
    description:
      "Loaded with fresh vegetables and mozzarella cheese.",
    price: 299,
    originalPrice: 349,
    rating: 4.6,
    ratingCount: "1.5K+",
    bestseller: true,
    veg: true,
    spicy: false,
    calories: 480,
    image:
      "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: 104,
    restaurantId: 2,
    name: "Cheese Burst Pizza",
    category: "Pizza",
    description:
      "Crispy crust with an irresistible cheese-filled centre.",
    price: 349,
    originalPrice: 399,
    rating: 4.7,
    ratingCount: "1.1K+",
    bestseller: false,
    veg: true,
    spicy: false,
    calories: 570,
    image:
      "https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: 105,
    restaurantId: 3,
    name: "Classic Chicken Burger",
    category: "Burger",
    description:
      "Crispy chicken patty with lettuce, cheese and special sauce.",
    price: 199,
    originalPrice: 249,
    rating: 4.5,
    ratingCount: "1.9K+",
    bestseller: true,
    veg: false,
    spicy: false,
    calories: 450,
    image:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: 106,
    restaurantId: 4,
    name: "Masala Dosa",
    category: "South Indian",
    description:
      "Golden crispy dosa served with chutney and sambar.",
    price: 99,
    originalPrice: 129,
    rating: 4.8,
    ratingCount: "3.2K+",
    bestseller: true,
    veg: true,
    spicy: true,
    calories: 310,
    image:
      "https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: 107,
    restaurantId: 4,
    name: "Idli Vada Combo",
    category: "South Indian",
    description:
      "Soft idlis and crispy vada served with sambar.",
    price: 129,
    originalPrice: 149,
    rating: 4.6,
    ratingCount: "2.1K+",
    bestseller: false,
    veg: true,
    spicy: false,
    calories: 290,
    image:
      "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: 108,
    restaurantId: 5,
    name: "Hakka Noodles",
    category: "Chinese",
    description:
      "Wok tossed noodles with vegetables and Asian sauces.",
    price: 179,
    originalPrice: 219,
    rating: 4.4,
    ratingCount: "1.3K+",
    bestseller: true,
    veg: true,
    spicy: true,
    calories: 390,
    image:
      "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: 109,
    restaurantId: 6,
    name: "Butter Chicken",
    category: "North Indian",
    description:
      "Creamy tomato gravy with tender tandoori chicken.",
    price: 289,
    originalPrice: 329,
    rating: 4.7,
    ratingCount: "2.0K+",
    bestseller: true,
    veg: false,
    spicy: true,
    calories: 580,
    image:
      "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: 110,
    restaurantId: 7,
    name: "Chocolate Sundae",
    category: "Desserts",
    description:
      "Rich chocolate ice cream topped with chocolate sauce.",
    price: 159,
    originalPrice: 189,
    rating: 4.8,
    ratingCount: "2.7K+",
    bestseller: true,
    veg: true,
    spicy: false,
    calories: 360,
    image:
      "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: 111,
    restaurantId: 8,
    name: "Fresh Power Bowl",
    category: "Healthy",
    description:
      "Fresh vegetables, quinoa, avocado and nutritious toppings.",
    price: 229,
    originalPrice: 279,
    rating: 4.5,
    ratingCount: "1.2K+",
    bestseller: true,
    veg: true,
    spicy: false,
    calories: 320,
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: 112,
    restaurantId: 7,
    name: "Cold Coffee",
    category: "Drinks",
    description:
      "Creamy chilled coffee blended with premium ice cream.",
    price: 139,
    originalPrice: 169,
    rating: 4.6,
    ratingCount: "1.4K+",
    bestseller: false,
    veg: true,
    spicy: false,
    calories: 250,
    image:
      "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=800&q=85",
  },
];
const cityRestaurantSeeds = [
  { id: 9, city: "Chennai", area: "Velachery", name: "Coastal Spice Kitchen", cuisine: "South Indian • Seafood • Biryani", tags: ["South Indian", "Biryani"], rating: 4.6, time: 29, price: "₹450 for two", offer: "30% OFF", veg: false, image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1000&q=85" },
  { id: 10, city: "Chennai", area: "Mylapore", name: "Madras Tiffin Lab", cuisine: "South Indian • Breakfast • Snacks", tags: ["South Indian", "Street Food"], rating: 4.7, time: 18, price: "₹280 for two", offer: "₹75 OFF", veg: true, image: "https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=1000&q=85" },
  { id: 11, city: "Bengaluru", area: "Indiranagar", name: "Bengaluru Bowl Co.", cuisine: "Healthy • Continental • Salads", tags: ["Healthy"], rating: 4.7, time: 24, price: "₹500 for two", offer: "25% OFF", veg: true, image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85" },
  { id: 12, city: "Bengaluru", area: "Koramangala", name: "Namma Biryani House", cuisine: "Biryani • Kebabs • Mughlai", tags: ["Biryani", "Chicken"], rating: 4.8, time: 27, price: "₹420 for two", offer: "50% OFF up to ₹120", veg: false, image: "https://images.unsplash.com/photo-1631515242808-497c3fbd3972?auto=format&fit=crop&w=1000&q=85" },
  { id: 13, city: "Hyderabad", area: "Banjara Hills", name: "Deccan Dum", cuisine: "Biryani • Mughlai • Kebabs", tags: ["Biryani", "Chicken"], rating: 4.9, time: 26, price: "₹500 for two", offer: "₹125 OFF", veg: false, image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=1000&q=85" },
  { id: 14, city: "Hyderabad", area: "Madhapur", name: "Charminar Street Eats", cuisine: "Street Food • Shawarma • Snacks", tags: ["Street Food", "Shawarma"], rating: 4.5, time: 22, price: "₹300 for two", offer: "20% OFF", veg: false, image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=1000&q=85" },
  { id: 15, city: "Coimbatore", area: "RS Puram", name: "Kovai Spice Route", cuisine: "South Indian • Biryani • Chinese", tags: ["South Indian", "Biryani", "Chinese"], rating: 4.6, time: 25, price: "₹380 for two", offer: "30% OFF", veg: false, image: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=1000&q=85" },
  { id: 16, city: "Coimbatore", area: "Gandhipuram", name: "Bowl & Brew", cuisine: "Burgers • Beverages • Fast Food", tags: ["Burger", "Drinks"], rating: 4.4, time: 21, price: "₹350 for two", offer: "FREE DELIVERY", veg: true, image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1000&q=85" },
  { id: 17, city: "Madurai", area: "KK Nagar", name: "Madurai Mess 24", cuisine: "South Indian • Biryani • Meals", tags: ["South Indian", "Biryani"], rating: 4.8, time: 23, price: "₹320 for two", offer: "₹100 OFF", veg: false, image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=1000&q=85" },
  { id: 18, city: "Madurai", area: "Anna Nagar", name: "Jigarthanda Junction", cuisine: "Desserts • Drinks • Snacks", tags: ["Desserts", "Drinks"], rating: 4.7, time: 17, price: "₹250 for two", offer: "BUY 1 GET 1", veg: true, image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=1000&q=85" },
  { id: 19, city: "Kochi", area: "Kakkanad", name: "Malabar Table", cuisine: "Kerala • Seafood • Biryani", tags: ["Biryani", "Chicken"], rating: 4.7, time: 31, price: "₹480 for two", offer: "20% OFF", veg: false, image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1000&q=85" },
  { id: 20, city: "Kochi", area: "Panampilly Nagar", name: "Coco & Curry", cuisine: "Asian • Thai • Healthy", tags: ["Chinese", "Healthy"], rating: 4.5, time: 28, price: "₹550 for two", offer: "₹150 OFF", veg: true, image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85" },
  { id: 21, city: "Mumbai", area: "Andheri West", name: "Bombay Tadka House", cuisine: "North Indian • Street Food • Kebabs", tags: ["North Indian", "Street Food"], rating: 4.6, time: 30, price: "₹450 for two", offer: "40% OFF", veg: false, image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1000&q=85" },
  { id: 22, city: "Mumbai", area: "Powai", name: "Mumbai Pizza Social", cuisine: "Pizza • Italian • Fast Food", tags: ["Pizza", "Fast Food"], rating: 4.5, time: 24, price: "₹550 for two", offer: "₹125 OFF", veg: true, image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1000&q=85" },
  { id: 23, city: "Pune", area: "Kothrud", name: "Deccan Dosa Co.", cuisine: "South Indian • Breakfast • Snacks", tags: ["South Indian", "Street Food"], rating: 4.7, time: 20, price: "₹300 for two", offer: "25% OFF", veg: true, image: "https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=1000&q=85" },
  { id: 24, city: "Pune", area: "Viman Nagar", name: "Momo Republic", cuisine: "Momos • Chinese • Asian", tags: ["Momos", "Chinese"], rating: 4.6, time: 23, price: "₹350 for two", offer: "₹100 OFF", veg: true, image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=1000&q=85" },
  { id: 25, city: "Delhi", area: "Saket", name: "Dilli Zaika", cuisine: "North Indian • Mughlai • Kebabs", tags: ["North Indian", "Chicken"], rating: 4.8, time: 28, price: "₹500 for two", offer: "30% OFF", veg: false, image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=1000&q=85" },
  { id: 26, city: "Delhi", area: "Rajouri Garden", name: "Capital Shawarma", cuisine: "Shawarma • Fast Food • Arabian", tags: ["Shawarma", "Fast Food"], rating: 4.5, time: 19, price: "₹320 for two", offer: "FREE DELIVERY", veg: false, image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=1000&q=85" },
];
const additionalRestaurants = cityRestaurantSeeds.map((item) => ({
  id: item.id,
  name: item.name,
  cuisine: item.cuisine,
  tags: item.tags,
  location: `${item.area}, ${item.city}`,
  city: item.city,
  rating: item.rating,
  ratingCount: `${Math.floor(item.rating * 1100)}+`,
  deliveryTime: `${item.time}-${item.time + 5} mins`,
  deliveryMinutes: item.time,
  priceForTwo: item.price,
  image: item.image,
  offer: item.offer,
  promoted: item.id % 3 === 0,
  veg: item.veg,
  distance: `${(1.2 + (item.id % 5) * 0.7).toFixed(1)} km`,
  distanceValue: 1.2 + (item.id % 5) * 0.7,
  isOpen: true,
  freeDelivery: item.offer.includes("FREE") || item.time <= 20,
  deliveryFee: item.offer.includes("FREE") || item.time <= 20 ? 0 : 29,
  popular: item.rating >= 4.6,
}));
const normalizedRestaurants = [...baseRestaurants.map((r) => ({
  ...r,
  city: r.city || (r.location?.split(",").pop()?.trim() || "Chennai"),
})), ...additionalRestaurants];
const extraMenuTemplates = [
  { suffix: "Signature Combo", category: "Biryani", price: 279, originalPrice: 329, veg: false, spicy: true, image: "https://images.unsplash.com/photo-1631515242808-497c3fbd3972?auto=format&fit=crop&w=800&q=85" },
  { suffix: "Loaded Special", category: "Fast Food", price: 219, originalPrice: 259, veg: true, spicy: false, image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=85" },
  { suffix: "Chef's Favourite", category: "Chinese", price: 229, originalPrice: 279, veg: true, spicy: true, image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=85" },
];
const additionalMenuItems = cityRestaurantSeeds.flatMap((r, index) => {
  const restaurant = additionalRestaurants[index];
  const primary = r.tags[0] || "Fast Food";
  const image = r.image;
  return [
    {
      id: 1000 + index * 3 + 1,
      restaurantId: restaurant.id,
      name: `${r.name} ${primary} Special`,
      category: primary,
      description: `A signature favourite from ${r.name}, freshly prepared with bold flavours and premium ingredients.`,
      price: 189 + (index % 5) * 25,
      originalPrice: 229 + (index % 5) * 25,
      rating: r.rating,
      ratingCount: `${700 + index * 83}+`,
      bestseller: index % 2 === 0,
      veg: r.veg,
      spicy: index % 3 === 0,
      calories: 320 + index * 11,
      image,
    },
    {
      id: 1000 + index * 3 + 2,
      restaurantId: restaurant.id,
      name: `${r.name} Family Combo`,
      category: r.tags[1] || primary,
      description: `A generous sharing combo designed for a satisfying meal with friends and family.`,
      price: 299 + (index % 4) * 35,
      originalPrice: 359 + (index % 4) * 35,
      rating: Math.max(4.3, r.rating - 0.1),
      ratingCount: `${500 + index * 61}+`,
      bestseller: index % 3 === 0,
      veg: r.veg,
      spicy: index % 2 === 1,
      calories: 540 + index * 14,
      image,
    },
    {
      id: 1000 + index * 3 + 3,
      restaurantId: restaurant.id,
      name: `${r.name} Quick Bite`,
      category: r.tags[0] || primary,
      description: `Quick, comforting and packed with the flavours customers love.`,
      price: 129 + (index % 6) * 15,
      originalPrice: 159 + (index % 6) * 15,
      rating: Math.max(4.2, r.rating - 0.2),
      ratingCount: `${400 + index * 47}+`,
      bestseller: true,
      veg: r.veg,
      spicy: index % 4 === 0,
      calories: 250 + index * 9,
      image,
    },
  ];
});
export const restaurants = normalizedRestaurants;
export const menuItems = [...baseMenuItems, ...additionalMenuItems];
export const offers = [
  {
    id: 1,
    title: "50% OFF",
    subtitle: "On your first order",
    code: "WELCOME50",
    color: "orange",
    icon: "🔥",
  },
  {
    id: 2,
    title: "₹125 OFF",
    subtitle: "On orders above ₹499",
    code: "FOOD125",
    color: "purple",
    icon: "🎁",
  },
  {
    id: 3,
    title: "FREE DELIVERY",
    subtitle: "On selected restaurants",
    code: "FREEDEL",
    color: "green",
    icon: "🛵",
  },
  {
    id: 4,
    title: "20% OFF",
    subtitle: "Weekend special offer",
    code: "WEEKEND20",
    color: "blue",
    icon: "⚡",
  },
];
export const cities = [
  "Chennai",
  "Bengaluru",
  "Hyderabad",
  "Coimbatore",
  "Madurai",
  "Kochi",
];
export const searchSuggestions = [
  "Chicken Biryani",
  "Pizza",
  "Burger",
  "Dosa",
  "Chicken",
  "Chinese",
  "Desserts",
  "Healthy food",
  "Ice cream",
  "Butter Chicken",
];
export const liveDelivery = {
  ordersToday: 52348,
  activeOrders: 1287,
  averageDelivery: 27,
  deliveryPartners: 843,
};
export const features = [
  {
    id: 1,
    icon: "⚡",
    title: "Lightning Fast",
    description: "Average delivery under 30 minutes",
  },
  {
    id: 2,
    icon: "🛡️",
    title: "Safe & Secure",
    description: "Protected payments every time",
  },
  {
    id: 3,
    icon: "⭐",
    title: "Top Rated",
    description: "Only the best restaurants",
  },
  {
    id: 4,
    icon: "🎁",
    title: "Daily Offers",
    description: "Save more on every order",
  },
];
export const testimonials = [
  {
    id: 1,
    name: "Priya",
    location: "Chennai",
    rating: 5,
    text: "The delivery was incredibly fast and the food arrived perfectly packed!",
    avatar: "https://i.pravatar.cc/100?img=47",
  },
  {
    id: 2,
    name: "Arun",
    location: "Bengaluru",
    rating: 5,
    text: "FoodGo has become my go-to app for biryani and weekend food orders.",
    avatar: "https://i.pravatar.cc/100?img=12",
  },
  {
    id: 3,
    name: "Meena",
    location: "Coimbatore",
    rating: 4,
    text: "Great restaurant selection, useful offers and a very smooth experience.",
    avatar: "https://i.pravatar.cc/100?img=32",
  },
];
export const navLinks = [
  {
    label: "Home",
    path: "/",
  },
  {
    label: "Restaurants",
    path: "/restaurants",
  },
  {
    label: "Orders",
    path: "/orders",
  },
  {
    label: "About",
    path: "/about",
  },
  {
    label: "Contact",
    path: "/contact",
  },
];
